import { type NextPage } from "next";
import Head from "next/head";
import AddUrl from "../components/AddUrl";
import User from "../components/User";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Url-Shortener</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen flex-col items-center  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <User />
        <AddUrl />
      </main>
    </>
  );
};

export default Home;
